### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Mike4U** [aemayer/amserial#1]
Don't see how to thank authors so I'll do it here !
Started using amserial somehow back around Nov 2003 on a personal home automation app I changed to cocoa.  Has worked reliably  since.  I didn't know you were on GitHub. Have upgraded myself or found your updates many times.

Thanks !

**Comment by seanm** [comment]
Glad to hear, thanks.

If ever you find issues, or want to discuss potential changes, I'm here...

**Comment by seanm** [comment]
@Mike4U if you're interested, I've just pushed some updates.
